# Generated by Django 3.2.4 on 2021-07-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('ip_Address', models.FloatField()),
                ('date_time', models.DateField()),
                ('aandom', models.IntegerField()),
            ],
        ),
    ]
