# Generated by Django 3.2.4 on 2021-07-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0002_rename_ip_address_data_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='aandom',
            new_name='n',
        ),
    ]
