# Generated by Django 3.2.4 on 2021-07-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0003_rename_aandom_data_n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
