# Generated by Django 3.2.4 on 2021-07-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0004_alter_data_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_time',
            field=models.TimeField(),
        ),
    ]
