# Generated by Django 3.2.4 on 2021-07-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0005_alter_data_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
