# Generated by Django 3.2.4 on 2021-07-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0008_alter_data_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
