# Generated by Django 3.2.4 on 2021-07-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0009_alter_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_time',
            field=models.TimeField(),
        ),
    ]
